# Generated by Django 2.1.1 on 2018-10-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warden', models.CharField(max_length=20)),
                ('no_of_roooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField(default=2)),
                ('hostelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.rooms')),
            ],
        ),
    ]
