# Generated by Django 2.1.1 on 2018-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_hostel_rooms_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='no_of_roooms',
            new_name='no_of_rooms',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='no_of_students',
            field=models.IntegerField(),
        ),
    ]
